name: Test Action Workflow

# detta körs varje gång man gör en pull request
on:
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
    services:
      db:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: django_db
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
      - name: Run Migrations
        run: |
          python blog_project/manage.py migrate
      - name: Run Tests
        run: |
          python blog_project/manage.py test